Repository DeliveryImpossible/DeliveryRun, pull requests merged in 2022-02, with the labels that each got.

#32 Feat/27 playerrespawn
  DeliveryRun/Assets/Prefabs/Item.meta
  DeliveryRun/Assets/Prefabs/Player.prefab
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
  DeliveryRun/Assets/Scripts/Player/PlayerRespwan.cs
  DeliveryRun/Assets/Scripts/Player/PlayerRespwan.cs.meta
Labels: FEAT, yejin🎀

#35 [FIX] #34 - item prefab 제거
  DeliveryRun/Assets/Prefabs/GameItem.prefab
  DeliveryRun/Assets/Prefabs/GameItem.prefab.meta
  DeliveryRun/Assets/Prefabs/Temp.meta
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
  DeliveryRun/Assets/UI/Images.meta
  DeliveryRun/ProjectSettings/ProjectSettings.asset
Labels: FIX, junghyun🎠

#41 Feature/37 fix cloth animator
  DeliveryRun/Assets/Prefabs/Player.prefab
  DeliveryRun/Assets/Prefabs/Temp.meta
  DeliveryRun/Assets/Resources/Enemy.prefab
  DeliveryRun/Assets/Scenes/4_MapSelection.meta
  DeliveryRun/Assets/Scenes/4_MapSelection/LightingData.asset
  DeliveryRun/Assets/Scenes/4_MapSelection/LightingData.asset.meta
  DeliveryRun/Assets/Scenes/4_MapSelection/ReflectionProbe-0.exr
  DeliveryRun/Assets/Scenes/4_MapSelection/ReflectionProbe-0.exr.meta
  DeliveryRun/Assets/Scripts/MapSelect/LoadGameScene.cs
  DeliveryRun/Assets/UI/Images.meta
Labels: FIX, junghyun🎠

#44 [FIX] #43 item 오류 고치기
  DeliveryRun/Assets/Prefabs/Temp.meta
  DeliveryRun/Assets/Scripts/Audio/ItemSoundEffect.cs
  DeliveryRun/Assets/Scripts/InGameItems.cs
  DeliveryRun/Assets/Scripts/Player/Joystick.cs
  DeliveryRun/Assets/Scripts/Save/InGameSave.cs
  DeliveryRun/Assets/UI/Images.meta
Labels: FIX, junghyun🎠

#47 Feature/33 game manual
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scripts/Tutorial.cs
  DeliveryRun/Assets/Scripts/Tutorial.cs.meta
  DeliveryRun/Assets/Scripts/UI/SceneStart.cs
  DeliveryRun/Assets/Scripts/UIDescription.cs
  DeliveryRun/Assets/Scripts/UIDescription.cs.meta
  DeliveryRun/Assets/UI.meta
Labels: FEAT, chaeyeong👾

#48 Fix/24 deliver menu image
  DeliveryRun/Assets/Prefabs/Item.meta~main
  DeliveryRun/Assets/Prefabs/Managers.meta~HEAD
  DeliveryRun/Assets/Prefabs/Managers.meta~main
  DeliveryRun/Assets/Prefabs/UI.meta~HEAD
  DeliveryRun/Assets/Prefabs/UI.meta~main
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scripts/CheckRightTarget.cs
  DeliveryRun/Assets/Scripts/MakeReceipt.cs
Labels: FIX, chaeyeong👾
