Repository DeliveryImpossible/DeliveryRun, pull requests merged in 2022-01, with the labels that each got.

#14 [UPDATE] change lv1 and lv2
  DeliveryRun/Assets/Scenes/4_MapSelection.unity
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity.meta
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity.meta
  DeliveryRun/Assets/Scripts/MapSelect/MapName.cs
  DeliveryRun/ProjectSettings/EditorBuildSettings.asset
Labels: UPDATE, yejin🎀

#15 Feature/5 enemy&item random location
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
Labels: FEAT, junghyun🎠

#18 Update/4-charactermoving
  DeliveryRun/Assets/Prefabs/Player.prefab
  DeliveryRun/Assets/Scenes/4_MapSelection.unity
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
  DeliveryRun/Assets/Scripts/Audio/AudioManager.cs
  DeliveryRun/Assets/Scripts/Player/Joystick.cs
  DeliveryRun/Assets/Scripts/Player/RoateCam.cs
  DeliveryRun/Assets/Scripts/Player/RotateCam.cs
  DeliveryRun/Assets/Scripts/Player/RotateCam.cs.meta
  DeliveryRun/Assets/Scripts/UI/ButtonSceneChange.cs
  DeliveryRun/Assets/Scripts/UI/UiActiveController.cs
  DeliveryRun/ProjectSettings/TagManager.asset
Labels: UPDATE, yejin🎀

#19 Fix/2 cameramoving
  DeliveryRun/Assets/Prefabs/Player.prefab
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
Labels: FIX, yejin🎀

#20 [UPDATE] add hair & cap
  DeliveryRun/Assets/Scripts/RandomClothing.cs
Labels: UPDATE, junghyun🎠

#25 Fix/23 random location script
  DeliveryRun/Assets/Scripts/EnemySpawner.cs
  DeliveryRun/Assets/Scripts/ItemSpawner.cs
  DeliveryRun/Assets/Scripts/RandomLocation.cs
  DeliveryRun/Assets/UI.meta
  DeliveryRun/Assets/UI/Images.meta
Labels: FIX, junghyun🎠

#28 Fix/26 timeerror
  DeliveryRun/Assets/Prefabs/Player.prefab
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scenes/6_Lv2_village.unity
  DeliveryRun/Assets/Scripts/CheckDeliverZone.cs
  DeliveryRun/Assets/Scripts/CheckRightTarget.cs
  DeliveryRun/Assets/Scripts/FilePath.cs
  DeliveryRun/Assets/Scripts/FilePath.cs.meta
  DeliveryRun/Assets/Scripts/InGameItems.cs
  DeliveryRun/Assets/Scripts/Player/Joystick.cs
  DeliveryRun/Assets/Scripts/Player/RotateCam.cs
  DeliveryRun/Assets/Scripts/Result/GetResult.cs
  DeliveryRun/Assets/Scripts/Result/ResetGame.cs
  DeliveryRun/Assets/Scripts/Save/FilePath.cs
  DeliveryRun/Assets/Scripts/Save/FilePath.cs.meta
  DeliveryRun/Assets/Scripts/Save/InGameSave.cs
  DeliveryRun/Assets/Scripts/UI/CircularTimerController.cs
  DeliveryRun/ProjectSettings/PackageManagerSettings.asset
  DeliveryRun/ProjectSettings/ProjectVersion.txt
Labels: FIX, yejin🎀

#30 fix/Prefab 문제 해결
  .gitignore
  DeliveryRun/Assets/Prefabs/GameItem.prefab
  DeliveryRun/Assets/Prefabs/GameItem.prefab.meta
  DeliveryRun/Assets/Prefabs/Item.meta
  DeliveryRun/Assets/Prefabs/Item.prefab
  DeliveryRun/Assets/Prefabs/Item.prefab.meta
  DeliveryRun/Assets/Prefabs/Items.prefab
  DeliveryRun/Assets/Prefabs/Items.prefab.meta
  DeliveryRun/Assets/Prefabs/Managers.meta
  DeliveryRun/Assets/Prefabs/Managers/GameEffectAudioManager.prefab
  DeliveryRun/Assets/Prefabs/Managers/GameEffectAudioManager.prefab.meta
  DeliveryRun/Assets/Prefabs/Managers/GameManager.prefab
  DeliveryRun/Assets/Prefabs/Managers/GameManager.prefab.meta
  DeliveryRun/Assets/Prefabs/Managers/Manager.prefab
  DeliveryRun/Assets/Prefabs/Managers/Manager.prefab.meta
  DeliveryRun/Assets/Prefabs/Managers/TargetManager.prefab
  DeliveryRun/Assets/Prefabs/Managers/TargetManager.prefab.meta
  DeliveryRun/Assets/Prefabs/UI.meta
  DeliveryRun/Assets/Prefabs/UI/Coin.prefab
  DeliveryRun/Assets/Prefabs/UI/Coin.prefab.meta
  DeliveryRun/Assets/Prefabs/UI/Level.prefab
  DeliveryRun/Assets/Prefabs/UI/Level.prefab.meta
  DeliveryRun/Assets/Prefabs/UI/Name.prefab
  DeliveryRun/Assets/Prefabs/UI/Name.prefab.meta
  DeliveryRun/Assets/Prefabs/UI/UI.prefab
  DeliveryRun/Assets/Prefabs/UI/UI.prefab.meta
  DeliveryRun/Assets/Scripts/InGameItems.cs
Labels: FIX

#31 [FIX] 플레이어 걷지 않음
  DeliveryRun/Assets/Prefabs/UI/UI.prefab
Labels: FIX
