Repository DeliveryImpossible/DeliveryRun, pull requests merged in 2022-04, with the labels that each got.

#68 [FIX] #33 - 튜토리얼 한번 하고 꺼지게 수정
  DeliveryRun/Assets/Scripts/Tutorial.cs
  DeliveryRun/Assets/Scripts/UI/SceneStart.cs
Labels: FIX, chaeyeong👾

#77 Update/71 arrangeingameview
  DeliveryRun/Assets/Images/UI/Buttons/Pause.png
  DeliveryRun/Assets/Images/UI/Buttons/Pause.png.meta
  DeliveryRun/Assets/Prefabs/UI/UI.prefab
  DeliveryRun/Assets/Scripts/Inventory.meta
  DeliveryRun/Assets/Scripts/Inventory/LoadInventory.cs
  DeliveryRun/Assets/Scripts/Inventory/LoadInventory.cs.meta
  DeliveryRun/Assets/Scripts/Inventory/PackingItems.cs
  DeliveryRun/Assets/Scripts/Inventory/PackingItems.cs.meta
Labels: UPDATE

#76 Feature/72 circular time controller
  DeliveryRun/Assets/Scripts/UI/CircularTimerController.cs
Labels: FEAT, junghyun🎠

#78 [FIX] 날아간 pause 복귀
  DeliveryRun/Assets/Prefabs/UI/UI.prefab
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
  DeliveryRun/Assets/Scripts/Save/Pause.cs
Labels: FIX
