Repository DeliveryImpossible/DeliveryRun, pull requests merged in 2022-03, with the labels that each got.

#49 [FEAT] Prologue
  DeliveryRun/Assets/Resources/PrologueScript.json
  DeliveryRun/Assets/Resources/PrologueScript.json.meta
  DeliveryRun/Assets/Scenes/0_Prologue.unity
  DeliveryRun/Assets/Scenes/0_Prologue.unity.meta
  DeliveryRun/Assets/Scripts/CheckRightTarget.cs
  DeliveryRun/Assets/Scripts/MapSelect/LoadGameScene.cs
  DeliveryRun/Assets/Scripts/Prologue.meta
  DeliveryRun/Assets/Scripts/Prologue/DialogueParser.cs
  DeliveryRun/Assets/Scripts/Prologue/DialogueParser.cs.meta
  DeliveryRun/Assets/Scripts/Prologue/PrologueAnimations.cs
  DeliveryRun/Assets/Scripts/Prologue/PrologueAnimations.cs.meta
  DeliveryRun/Assets/Scripts/Prologue/PrologueManager.cs
  DeliveryRun/Assets/Scripts/Prologue/PrologueManager.cs.meta
  DeliveryRun/Assets/Scripts/Prologue/PrologueNextButton.cs
  DeliveryRun/Assets/Scripts/Prologue/PrologueNextButton.cs.meta
  DeliveryRun/Assets/Scripts/UI/CircularTimerController.cs
  DeliveryRun/Assets/Scripts/UI/NameSettingButton.cs
  DeliveryRun/Assets/Scripts/UI/ScenesNameConst.cs
  DeliveryRun/ProjectSettings/EditorBuildSettings.asset
Labels: FEAT, yejin🎀

#54 Feat/46 prologue
  DeliveryRun/Assets/Scenes/0_GetPlayerName.unity
  DeliveryRun/Assets/Scripts/Audio/AudioManager.cs
  DeliveryRun/Assets/Scripts/MapSelect/LoadGameScene.cs
  DeliveryRun/Assets/Scripts/Prologue/PrologueManager.cs
Labels: FEAT, yejin🎀

#57 [FIX] lv1 missing item
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
Labels: FIX, junghyun🎠

#59 Fix/52 errors
  DeliveryRun/Assets/Scenes/5_Lv1_city.unity
Labels: FIX

#62 Fix/60 gameresulterror
  DeliveryRun/Assets/Scenes/0_GetPlayerName.unity
  DeliveryRun/Assets/Scripts/InventoryStore/Inventory/PackingItems.cs
  DeliveryRun/Assets/Scripts/Player/GetPackedItems.cs
  DeliveryRun/Assets/Scripts/Player/InGameBag.cs
  DeliveryRun/Assets/Scripts/Result/GetResult.cs
  DeliveryRun/Assets/Scripts/Save/InGameSave.cs
Labels: FIX, yejin🎀

#66 [FIX] 맵 성적 저장 오류
  DeliveryRun/Assets/Scripts/MapSelect/LoadGameScene.cs
  DeliveryRun/Assets/Scripts/MapSelect/MapInfo.cs
  DeliveryRun/Assets/Scripts/Save/SaveResult.cs
Labels: FIX, yejin🎀

#67 [FEAT] 게임 중간에 나가면 아이템 초기화
  DeliveryRun/Assets/Scenes/0_GetPlayerName.unity
  DeliveryRun/Assets/Scripts/CheckRightTarget.cs
  DeliveryRun/Assets/Scripts/InGameItems.cs
  DeliveryRun/Assets/Scripts/Player/GetPackedItems.cs
  DeliveryRun/Assets/Scripts/Save/InGameSave.cs
  DeliveryRun/Assets/Scripts/Save/ResetToStart.cs
  DeliveryRun/Assets/Scripts/Save/ResetToStart.cs.meta
  DeliveryRun/Assets/Scripts/UI/CircularTimerController.cs
  DeliveryRun/Assets/Scripts/UI/SceneStart.cs
Labels: FEAT, yejin🎀

#69 Feature/65 item
  DeliveryRun/Assets/Scripts/Audio/ItemSoundEffect.cs
  DeliveryRun/Assets/Scripts/InGameItems.cs
  DeliveryRun/Assets/Scripts/Player/InGameBag.cs
Labels: FIX, junghyun🎠
